name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run Docker containers
        run: |
          docker-compose down
          docker-compose up --build -d 

      - name: Build Docker image
        run: |
          docker images
          docker build -t api-app .

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag and push Docker image
        run: |
          docker tag api-app thinhnd24/spring-app
          docker push thinhnd24/spring-app

      - name: Trigger deploy on Render
        run: |
          curl -X POST https://api.render.com/deploy/srv-d045p0adbo4c73e9iv9g?key=xtiRl3rX5lo

      - name: Checkout gh-pages branch
        run: |
          git clone --branch gh-pages https://github.com/<username>/<repository>.git gh-pages

      - name: Copy index.html to gh-pages
        run: |
          cp target/site/jacoco/index.html gh-pages/

      - name: Commit and push to gh-pages
        run: |
          cd gh-pages
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git add index.html
          git commit -m "Deploy index.html to GitHub Pages"
          git push origin gh-pages
