name: CI/CD Pipeline

on:
  push:
    branches:
      - dev  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run Docker containers
        run: |
          docker-compose down
          docker-compose up --build -d 

      - name: Build Docker image
        run: |
          docker images
          docker build -t api-app .

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" 

      - name: Tag and push Docker image
        run: |
          docker tag api-app thinhnd24/spring-app
          docker push thinhnd24/spring-app
        